/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user1' at '16. 8. 31 오전 11:01' with Gradle 2.14.1
 *
 * @author user1, @date 16. 8. 31 오전 11:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
